package abdaty_technologie.API_Invest.Entity.Enum;

public enum DomaineActiviteNr {
    CULTURE_DU_CACAO("Culture du cacao"),
    CULTURE_DU_CAFE("Culture du café"),
    HEVEA_CULTURE("Hévéaculture"),
    CULTURE_DU_COTON("Culture du coton"),
    CULTURE_BANANE_ANANAS_MANGUE("Culture de la banane douce, de l'ananas et de la mangue"),
    CULTURE_ANACARDE("Culture de l'anacarde"),
    CULTURE_CANNE_A_SUCRE("Culture de la canne à sucre"),
    CULTURE_GRAINES_OLEAGINEUX("Culture de graines et fruits oléagineux"),
    HORTICULTURE_REPRODUCTION_PLANTES("Horticulture et reproduction des plantes"),
    CULTURE_AUTRES_PRODUITS_INDUSTRIE("Culture d'autres produits destinés à l'industrie ou à l'exportation"),
    ELEVAGE("Élevage"),
    CHASSE("Chasse"),
    ACTIVITES_SOUTIEN_AGRICULTURE("Activités de soutien à l'agriculture"),
    ACTIVITES_SOUTIEN_ELEVAGE("Activités de soutien à l'élevage"),
    ACTIVITES_SOUTIEN_CHASSE("Activités de soutien à la chasse"),
    SYLVICULTURE("Sylviculture"),
    EXPLOITATION_FORESTIERE("Exploitation forestière"),
    PRODUCTION_CHARBON_BOIS("Production de charbon de bois"),
    ACTIVITES_SOUTIEN_SYLVICULTURE("Activités de soutien à la sylviculture et à l'exploitation forestière"),
    PECHE_MARITIME("Pêche maritime"),
    PECHE_EAU_DOUCE("Pêche en eau douce"),
    PISCICULTURE("Pisciculture"),
    AQUACULTURE("Aquaculture"),
    EXTRACTION_CHARBON_LIGNITE("Extraction de charbon et de lignite"),
    EXTRACTION_PETROLE_BRUT("Extraction de pétrole brut"),
    EXTRACTION_GAZ_NATUREL("Extraction de gaz naturel"),
    EXTRACTION_MINERAIS_FER("Extraction de minerais de fer"),
    EXTRACTION_MINERAIS_METAUX_PRECIEUX("Extraction de minerais de métaux précieux"),
    EXTRACTION_AUTRES_MINERAIS_NON_FERREUX("Extraction d'autres minerais de métaux non ferreux"),
    EXTRACTION_PIERRES_SABLES_ARGILES("Extraction de pierres, de sables et d'argiles"),
    EXTRACTION_PHOSPHATES_SELS_POTASSIUM("Extraction de phosphates et de sels de potassium naturels"),
    EXTRACTION_MINERAUX_INDUSTRIE_CHIMIQUE("Extractions de minéraux pour l'industrie chimique"),
    EXTRACTION_SEL_NATRON("Extraction ou production de sel et de natron"),
    EXTRACTION_PIERRES_PRECIEUSES("Extraction de pierres précieuses et semi-précieuses"),
    AUTRES_EXTRACTIONS("Autres extractions"),
    ACTIVITES_SOUTIEN_EXTRACTION_HYDROCARBURES("Activités de soutien à l'extraction d'hydrocarbures"),
    ACTIVITES_SOUTIEN_AUTRES_INDUSTRIES_EXTRACT("Activités de soutien aux autres industries extractives"),
    ABATTAGE_TRANSFORMATION_VIANDE("Abattage, transformation et conservation de la viande"),
    PREPARATION_PRODUITS_VIANDE("Préparation de produits à base de viande"),
    CONGELATION_POISSONS("Congélation de poissons, crustacés et mollusques"),
    SECHAGE_SALAGE_FUMAGE_POISSON("Séchage, salage ou fumage du poisson"),
    AUTRES_TRANSFORMATIONS_POISSONS("Autres transformations et conservation des poissons, crustacés et mollusques"),
    TRANSFORMATION_FRUITS_LEGUMES("Transformation et conservation de fruits et légumes"),
    FABRICATION_CORPS_GRAS("Fabrication de corps gras d'origine animale et végétale"),
    TRAVAIL_GRAINS("Travail des grains"),
    TRANSFORMATION_MANIOC("Transformation du manioc et fabrication de produits amylacés"),
    FABRICATION_PAIN_PATISSERIES("Fabrication de pain et de pâtisseries fraîches"),
    BISCUITERIE_PATISSERIE_CONSERVATION("Biscuiterie et pâtisserie de conservation"),
    FABRICATION_PATES_ALIMENTAIRES("Fabrication de pâtes alimentaires, de semoules et produits farineux similaires"),
    TRANSFORMATION_CACAO("Transformation du cacao"),
    TRANSFORMATION_CAFE("Transformation du café"),
    FABRICATION_PRODUITS_LAITIERS("Fabrication de produits laitiers et de glaces"),
    FABRICATION_SUCRE_CONFISERIE("Fabrication de sucre et de confiserie"),
    FABRICATION_THE("Fabrication de thé"),
    FABRICATION_CONDIMENTS("Fabrication de condiments et assaisonnements"),
    FABRICATION_ALIMENTS_ANIMAUX("Fabrication d'aliments pour animaux"),
    FABRICATION_DENREES_DIVERSES("Fabrication de denrées diverses n.c.a."),
    FABRICATION_MALT_BIERE("Fabrication de malt et de bière"),
    FABRICATION_AUTRES_BOISSONS_ALCOOLISEES("Fabrication d'autres boissons alcoolisées"),
    FABRICATION_BOISSONS_NON_ALCOOLISEES("Fabrication de boissons non alcoolisées et d'eaux minérales"),
    FABRICATION_PRODUITS_TABAC("Fabrication de produits à base de tabac"),
    FILATURE_TEXTILE("Filature de textile"),
    TISSAGE_TEXTILE("Tissage de textile"),
    ENNOBLISSEMENT_TEXTILE("Ennoblissement de textile"),
    FABRICATION_TAPIS_MOQUETTES("Fabrication de tapis et moquettes"),
    FABRICATION_ETOFFES_MAILLES("Fabrication d'étoffes à mailles et d'articles textiles non vestimentaires"),
    FABRICATION_VETEMENTS("Fabrication de vêtements"),
    SERVICE_COUTURE_MESURE("Service de couture sur mesure"),
    APPRET_TANNAGE_CUIRS("Apprêt, tannage des cuirs et fourrures"),
    FABRICATION_ARTICLES_VOYAGE("Fabrication d'articles de voyage, maroquinerie et sellerie"),
    FABRICATION_CHAUSSURES("Fabrication de chaussures et articles chaussants"),
    SCIAGE_RABOTAGE("Sciage, rabotage"),
    FABRICATION_PLACAGE_CONTREPLAQUE("Fabrication de feuilles de placage, contreplaqués et panneaux"),
    FABRICATION_OUVRAGES_CHARPENTE("Fabrication d'ouvrages de charpente, menuiseries et emballages en bois"),
    FABRICATION_ARTICLES_BOIS("Fabrication d'articles divers en bois ou liège, vannerie et sparterie"),
    FABRICATION_PATE_PAPIER("Fabrication de pâte à papier, papier et carton"),
    FABRICATION_CARTON_ONDULE("Fabrication de carton ondulé et emballages en papier ou carton"),
    FABRICATION_ARTICLES_PAPIER("Fabrication d'articles en papier ou carton"),
    IMPRIMERIE_ACTIVITES_CONNEXES("Imprimerie et activités connexes"),
    REPRODUCTION_ENREGISTREMENTS("Reproduction d'enregistrements"),
    RAFFINAGE_PETROLE("Raffinage du pétrole"),
    COKEFACTION("Cokéfaction"),
    FABRICATION_PRODUITS_AZOTES("Fabrication de produits azotés et d'engrais"),
    FABRICATION_AUTRES_PRODUITS_CHIMIQUES("Fabrication d'autres produits chimiques de base"),
    FABRICATION_SAVONS_DETERGENTS("Fabrication de savons, détergents et produits d'entretien"),
    FABRICATION_PARFUMS("Fabrication de parfums et produits de toilette"),
    FABRICATION_PRODUITS_AGROCHIMIQUES("Fabrication de produits agrochimiques"),
    FABRICATION_PEINTURES_VERNIS("Fabrication de peintures, vernis, adjuvants et encres"),
    FABRICATION_FIBRES_ARTIFICIELLES("Fabrication de fibres artificielles ou synthétiques"),
    FABRICATION_AUTRES_PRODUITS_CHIMIQUES_DIVERS("Fabrication d'autres produits chimiques"),
    INDUSTRIE_PHARMACEUTIQUE("Industrie pharmaceutique"),
    FABRICATION_MEDICAMENTS_TRADITIONNELS("Fabrication de médicaments traditionnels"),
    FABRICATION_PNEUMATIQUES("Fabrication et rechapage de pneumatiques"),
    FABRICATION_AUTRES_ARTICLES_CAOUTCHOUC("Fabrication d'autres articles en caoutchouc"),
    FABRICATION_ARTICLES_PLASTIQUE("Fabrication d'articles en plastique"),
    FABRICATION_VERRE("Fabrication de verre et d'articles en verre"),
    FABRICATION_CARREAUX_CERAMIQUE("Fabrication de carreaux en céramique"),
    FABRICATION_TUILES_BRIQUES("Fabrication de tuiles et briques"),
    FABRICATION_AUTRES_PRODUITS_CERAMIQUES("Fabrication d'autres produits céramiques"),
    FABRICATION_CIMENT_CHAUX("Fabrication de ciment, chaux et plâtre"),
    FABRICATION_MATERIAUX_CIMENT("Fabrication de matériaux et ouvrages en ciment, béton ou plâtre ; travail de la pierre"),
    FABRICATION_PRODUITS_MINERAUX_NON_METALLIQUES("Fabrication de produits minéraux non métalliques n.c.a."),
    SIDERURGIE("Sidérurgie et première transformation de l'acier"),
    METALLURGIE_METAUX_NON_FERREUX("Métallurgie et première transformation des métaux non ferreux"),
    FONDERIE("Fonderie"),
    FABRICATION_STRUCTURES_METALLIQUES("Fabrication de structures métalliques, citernes et ouvrages chaudronnés"),
    FABRICATION_AUTRES_OUVRAGES_METAUX("Fabrication d'autres ouvrages en métaux ; travail des métaux"),
    FABRICATION_COMPOSANTS_ELECTRONIQUES("Fabrication de composants, cartes électroniques et supports magnétiques"),
    FABRICATION_ORDINATEURS("Fabrication d'ordinateurs et d'équipements périphériques"),
    FABRICATION_EQUIPEMENTS_COMMUNICATION("Fabrication d'équipements de communication"),
    FABRICATION_PRODUITS_ELECTRONIQUES("Fabrication de produits électroniques grand public"),
    FABRICATION_EQUIPEMENTS_IMAGERIE_MEDICALE("Fabrication d'équipements d'imagerie médicale, de précision, d'optique et d'horlogerie"),
    FABRICATION_MACHINES_ELECTROTECHNIQUES("Fabrication de machines et matériels électrotechniques"),
    FABRICATION_APPAREILS_DOMESTIQUES("Fabrication d'appareils domestiques"),
    FABRICATION_AUTRES_MATERIELS_ELECTRIQUES("Fabrication d'autres matériels électriques"),
    FABRICATION_MACHINES_USAGE_GENERAL("Fabrication de machines d'usage général"),
    FABRICATION_MACHINES_USAGE_SPECIFIQUE("Fabrication de machines d'usage spécifique"),
    CONSTRUCTION_VEHICULES_AUTOMOBILES("Construction de véhicules automobiles"),
    CONSTRUCTION_NAVALE("Construction navale"),
    CONSTRUCTION_AERONAUTIQUE("Construction aéronautique"),
    CONSTRUCTION_FERROVIAIRE("Construction ferroviaire"),
    CONSTRUCTION_VEHICULES_MILITAIRES("Construction de véhicules militaires de combat"),
    FABRICATION_AUTRES_EQUIPEMENTS_TRANSPORT("Fabrication d'autres équipements de transport"),
    FABRICATION_MATELAS_SOMMIERS("Fabrication de matelas et sommiers"),
    FABRICATION_MEUBLES("Fabrication de meubles"),
    FABRICATION_BIJOUX("Fabrication de bijoux"),
    FABRICATION_INSTRUMENTS_MUSIQUE("Fabrication d'instruments de musique"),
    ACTIVITES_MANUFACTURIERES_NCA("Activités manufacturières n.c.a."),
    REPARATION_MACHINES_EQUIPEMENTS("Réparation de machines et d'équipements professionnels"),
    INSTALLATION_MACHINES_EQUIPEMENTS("Installation de machines et d'équipements professionnels"),
    PRODUCTION_TRANSPORT_ELECTRICITE("Production, transport et distribution d'électricité"),
    PRODUCTION_DISTRIBUTION_COMBUSTIBLES("Production et distribution de combustibles gazeux et de glace"),
    CAPTAGE_TRAITEMENT_EAU("Captage, traitement et distribution d'eau"),
    COLLECTE_TRAITEMENT_EAUX_USEES("Collecte et traitement des eaux usées"),
    COLLECTE_TRAITEMENT_DECHETS("Collecte, traitement et élimination des déchets"),
    RECUPERATION("Récupération"),
    DEPOLLUTION_GESTION_DECHETS("Dépollution et gestion des déchets"),
    PROMOTION_IMMOBILIERE("Promotion immobilière"),
    CONSTRUCTION_BATIMENTS_COMPLETS("Construction de bâtiments complets"),
    CONSTRUCTION_ROUTES_VOIES_FERREES("Construction de routes et voies ferrées"),
    CONSTRUCTION_RESEAUX_LIGNES("Construction de réseaux et de lignes"),
    CONSTRUCTION_AUTRES_OUVRAGES_GENIE_CIVIL("Construction d'autres ouvrages de génie civil"),
    DEMOLITION_PREPARATION_SITES("Démolition et préparation des sites"),
    TRAVAUX_INSTALLATION("Travaux d'installation"),
    TRAVAUX_FINITION("Travaux de finition"),
    AUTRES_TRAVAUX_SPECIALISES("Autres travaux spécialisés de construction"),
    COMMERCE_VEHICULES_AUTOMOBILES("Commerce de véhicules automobiles"),
    ENTRETIEN_REPARATION_VEHICULES("Entretien et réparation de véhicules automobiles"),
    COMMERCE_PIECES_DETACHEES_AUTO("Commerce de pièces détachées et accessoires automobiles"),
    COMMERCE_REPARATION_MOTOCYCLES("Commerce et réparation de motocycles"),
    ACTIVITES_INTERMEDIAIRES_COMMERCE_GROS("Activités des intermédiaires du commerce de gros"),
    COMMERCE_GROS_PRODUITS_AGRICOLES("Commerce de gros de produits agricoles bruts et d'aliments pour animaux"),
    COMMERCE_GROS_ANIMAUX_VIVANTS("Commerce de gros d'animaux vivants, peaux et cuirs"),
    COMMERCE_GROS_PRODUITS_ALIMENTAIRES("Commerce de gros de produits alimentaires, boissons et tabacs manufacturés"),
    COMMERCE_GROS_TEXTILES_HABILLEMENT("Commerce de gros de textiles, habillement et chaussures"),
    COMMERCE_GROS_PRODUITS_PHARMACEUTIQUES("Commerce de gros de produits pharmaceutiques et médicaux"),
    COMMERCE_GROS_BIENS_CONSOMMATION("Commerce de gros de biens de consommation non alimentaires divers"),
    COMMERCE_GROS_CARBURANTS("Commerce de gros de carburants et combustibles"),
    COMMERCE_GROS_BOIS("Commerce de gros de bois"),
    COMMERCE_GROS_MATERIAUX_CONSTRUCTION("Commerce de gros de matériaux de construction, quincaillerie et fournitures de plomberie"),
    COMMERCE_GROS_AUTRES_PRODUITS_INTERMEDIAIRES("Commerce de gros d'autres produits intermédiaires non agricoles"),
    COMMERCE_GROS_MACHINES_EQUIPEMENTS("Commerce de gros de machines, équipements et fournitures"),
    COMMERCE_GROS_AUTRES_EQUIP_INDUSTRIELS("Commerce de gros d'autres équipements industriels et fournitures diverses"),
    COMMERCE_GROS_NON_SPECIALISE("Commerce de gros non spécialisé"),
    COMMERCE_DETAIL_MAGASIN_NON_SPECIALISE("Commerce de détail en magasin non spécialisé"),
    COMMERCE_DETAIL_PRODUITS_ALIMENTAIRES("Commerce de détail en magasin spécialisé de produits alimentaires, boissons et tabacs"),
    COMMERCE_DETAIL_PRODUITS_PHARMACEUTIQUES("Commerce de détail de produits pharmaceutiques, médicaux et de beauté"),
    COMMERCE_DETAIL_TEXTILES_HABILLEMENT("Commerce de détail de textiles, habillement, chaussures et articles en cuir"),
    COMMERCE_DETAIL_EQUIPEMENT_DOMESTIQUE("Commerce de détail d'articles et appareils d'équipement domestique"),
    COMMERCE_DETAIL_QUINCAILLERIE("Commerce de détail de quincaillerie, peintures, verre, tapis et revêtements"),
    COMMERCE_DETAIL_LIVRES_JOURNAUX("Commerce de détail de livres, journaux, articles de sport et loisirs"),
    COMMERCE_DETAIL_EQUIPEMENTS_INFORMATIQUES("Commerce de détail d'équipements informatiques et télécoms"),
    COMMERCE_DETAIL_CARBURANTS("Commerce de détail de carburants automobiles"),
    COMMERCE_DETAIL_AUTRES_PRODUITS("Commerce de détail d'autres produits n.c.a."),
    COMMERCE_DETAIL_MARCHES_VIANDES("Commerce de détail sur marchés de viandes et poissons"),
    COMMERCE_DETAIL_MARCHES_FRUITS("Commerce de détail sur marchés de fruits et légumes"),
    COMMERCE_DETAIL_MARCHES_CEREALES("Commerce de détail sur marchés de céréales et autres produits alimentaires"),
    COMMERCE_DETAIL_MARCHES_TEXTILES("Commerce de détail sur marchés de textiles, habillement et cuir"),
    COMMERCE_DETAIL_MARCHES_NON_ALIMENTAIRES("Commerce de détail sur marchés d'articles non alimentaires"),
    AUTRES_COMMERCES_DETAIL_HORS_MAGASIN("Autres commerces de détail hors magasin"),
    TRANSPORTS_FERROVIAIRES("Transports ferroviaires"),
    TRANSPORTS_ROUTIERS_PASSAGERS("Transports routiers de passagers"),
    TRANSPORTS_ROUTIERS_MARCHANDISES("Transports routiers de marchandises"),
    TRANSPORTS_PAR_CONDUITES("Transports par conduites"),
    TRANSPORTS_MARITIMES_COTIERS("Transports maritimes et côtiers"),
    TRANSPORTS_FLUVIAUX("Transports fluviaux"),
    TRANSPORTS_AERIENS_PASSAGERS("Transports aériens de passagers"),
    TRANSPORTS_AERIENS_FRET("Transports aériens de fret et transports spatiaux"),
    ENTREPOSAGE("Entreposage"),
    MANUTENTION("Manutention"),
    EXPLOITATION_INFRASTRUCTURES_TRANSPORT("Exploitation d'infrastructures de transport"),
    ORGANISATION_TRANSPORT_FRET("Organisation du transport de fret"),
    ACTIVITES_SERVICE_POSTAL("Activités de service postal universel"),
    AUTRES_ACTIVITES_COURRIER("Autres activités de courrier et de distribution"),
    HEBERGEMENT("Hébergement"),
    RESTAURATION("Restauration"),
    ACTIVITES_DEBITS_BOISSONS("Activités des débits de boissons"),
    EDITION_LIVRES_PERIODIQUES("Édition de livres et périodiques"),
    EDITION_LOGICIELS("Édition de logiciels"),
    PRODUCTION_VIDEO("Production vidéo : cinéma et télévision"),
    PRODUCTION_AUDIO("Production audio et édition musicale"),
    EDITION_DIFFUSION_RADIO("Édition et diffusion de programmes radio"),
    PROGRAMMATION_TELEVISUELLE("Programmation télévisuelle et télédiffusion"),
    TELECOMMUNICATIONS("Télécommunications"),
    TELECOMS_ET_TIC("Télécoms et TIC"),
    PROGRAMMATION_INFORMATIQUE("Programmation informatique"),
    CONSEIL_ACTIVITES_INFORMATIQUES("Conseil et autres activités informatiques"),
    TRAITEMENT_DONNEES_HEBERGEMENT("Traitement de données, hébergement et portails Internet"),
    AUTRES_ACTIVITES_INFORMATION("Autres activités liées à l'information"),
    ACTIVITES_BANQUE_CENTRALE("Activités de banque centrale"),
    AUTRES_INTERMEDIATIONS_MONETAIRES("Autres intermédiations monétaires (banques commerciales)"),
    ACTIVITES_FONDS_PLACEMENT("Activités des fonds de placement, holdings et similaires"),
    ACTIVITES_MICROFINANCE("Activités de microfinance"),
    AUTRES_ACTIVITES_CREDIT("Autres activités de crédit et intermédiations non monétaires"),
    ASSURANCE_VIE("Assurance vie et caisses de retraite"),
    ASSURANCE_DOMMAGE("Assurance dommage et réassurance"),
    GESTION_FONDS_TIERS("Gestion de fonds pour tiers"),
    ACTIVITES_TRANSFERT_FONDS("Activités de transfert de fonds et auxiliaires financiers"),
    ACTIVITES_AUXILIAIRES_ASSURANCE("Activités d'auxiliaires d'assurance"),
    LOCATION_IMMOBILIERE("Location immobilière et activités sur biens propres"),
    ACTIVITES_AGENCES_IMMOBILIERES("Activités des agences immobilières"),
    ACTIVITES_JURIDIQUES("Activités juridiques"),
    ACTIVITES_COMPTABLES("Activités comptables"),
    ACTIVITES_SIEGES_SOCIAUX("Activités des sièges sociaux"),
    CONSEIL_GESTION("Conseil de gestion"),
    ACTIVITES_ARCHITECTURE_INGENIERIE("Activités d'architecture et d'ingénierie"),
    ACTIVITES_CONTROLE_ANALYSES("Activités de contrôle et analyses techniques"),
    RECHERCHE_DEVELOPPEMENT_SCIENCES_PHYS("Recherche-développement en sciences physiques et naturelles"),
    RECHERCHE_DEVELOPPEMENT_SCIENCES_HUM("Recherche-développement en sciences humaines et sociales"),
    PUBLICITE("Publicité"),
    ETUDES_MARCHE_SONDAGES("Études de marché et sondages"),
    ACTIVITES_SPECIALISEES_DESIGN("Activités spécialisées de design"),
    ACTIVITES_PHOTOGRAPHIQUES("Activités photographiques"),
    AUTRES_ACTIVITES_SPECIALISEES("Autres activités spécialisées, scientifiques et techniques n.c.a."),
    ACTIVITES_VETERINAIRES("Activités vétérinaires"),
    LOCATION_VEHICULES_AUTOMOBILES("Location de véhicules automobiles"),
    LOCATION_MACHINES_EQUIPEMENTS("Location de machines et équipements n.c.a."),
    LOCATION_ARTICLES_PERSONNELS("Location d'articles personnels et domestiques n.c.a."),
    GESTION_DROITS_PROPRIETE("Gestion des droits de propriété industrielle"),
    ACTIVITES_RESSOURCES_HUMAINES("Activités liées aux ressources humaines"),
    ACTIVITES_AGENCES_RESERVATION("Activités des agences de réservation et voyagistes"),
    ENQUETES_SECURITE("Enquêtes et sécurité"),
    ACTIVITES_COMBINEES_SOUTIEN_BATIMENTS("Activités combinées de soutien aux bâtiments"),
    ACTIVITES_NETTOYAGE("Activités de nettoyage"),
    AMENAGEMENT_PAYSAGER("Aménagement paysager"),
    ACTIVITES_BUREAU_ROUTAGE("Activités de bureau, routage et centres d'appels"),
    ORGANISATION_FOIRES_SALONS("Organisation de foires, salons et congrès"),
    ACTIVITES_SOUTIEN_ENTREPRISES("Activités de soutien aux entreprises n.c.a."),
    ACTIVITES_ADMINISTRATION_GENERALE("Activités d'administration générale, économique et sociale"),
    ACTIVITES_PREROGATIVE_PUBLIQUE("Activités de prérogative publique"),
    ACTIVITES_SECURITE_SOCIALE("Activités de sécurité sociale obligatoire"),
    ENSEIGNEMENT_PRE_PRIMAIRE("Enseignement pré-primaire et primaire"),
    ENSEIGNEMENT_SECONDAIRE_GENERAL("Enseignement secondaire général"),
    ENSEIGNEMENT_SECONDAIRE_TECHNIQUE("Enseignement secondaire technique ou professionnel"),
    ENSEIGNEMENT_SUPERIEUR("Enseignement supérieur"),
    ENSEIGNEMENT_POST_SECONDAIRE("Enseignement post-secondaire non supérieur"),
    AUTRES_ACTIVITES_ENSEIGNEMENT("Autres activités d'enseignement"),
    ACTIVITES_HOSPITALIERES("Activités hospitalières"),
    ACTIVITE_MEDECINS_DENTISTES("Activité des médecins et des dentistes"),
    ACTIVITES_TRADIPRATICIENS("Activités des tradipraticiens"),
    AUTRES_ACTIVITES_SANTE_HUMAINE("Autres activités pour la santé humaine"),
    ACTIVITES_HEBERGEMENT_MEDICO_SOCIAL("Activités d'hébergement médico-social et social"),
    ACTION_SOCIALE_SANS_HEBERGEMENT("Action sociale sans hébergement"),
    ACTIVITES_CREATIVES_ARTISTIQUES("Activités créatives, artistiques et de spectacle"),
    CONSERVATION_VALORISATION_PATRIMOINE("Conservation et valorisation du patrimoine"),
    ORGANISATION_JEUX_HASARD("Organisation de jeux de hasard et d'argent"),
    ACTIVITES_LIEES_SPORT("Activités liées au sport"),
    ACTIVITES_RECREATIVES_LOISIRS("Activités récréatives et de loisirs"),
    ACTIVITES_ORGANISATIONS_ECONOMIQUES("Activités des organisations économiques, patronales et professionnelles"),
    ACTIVITES_SYNDICATS_TRAVAILLEURS("Activités des syndicats de travailleurs"),
    ACTIVITES_ORGANISATIONS_RELIGIEUSES("Activités des organisations religieuses"),
    ACTIVITES_ORGANISATIONS_POLITIQUES("Activités des organisations politiques"),
    ACTIVITES_AUTRES_ORGANISATIONS_ASSOCIATIVES("Activités des autres organisations associatives"),
    REPARATION_ORDINATEURS_EQUIPEMENTS("Réparation d'ordinateurs et d'équipements périphériques"),
    REPARATION_EQUIPEMENTS_COMMUNICATION("Réparation d'équipements de communication"),
    REPARATION_BIENS_PERSONNELS("Réparation de biens personnels et domestiques"),
    LAVAGE_NETTOYAGE_TEXTILES("Lavage et nettoyage de textiles"),
    COIFFURE_SOINS_BEAUTE("Coiffure et soins de beauté"),
    SERVICES_FUNERAIRES("Services funéraires"),
    AUTRES_SERVICES_PERSONNELS("Autres services personnels n.c.a."),
    ACTIVITES_MENAGES_EMPLOYEURS("Activités des ménages en tant qu'employeurs de personnel domestique"),
    ACTIVITES_MENAGES_PRODUCTEURS_BIENS("Activités indifférenciées des ménages producteurs de biens pour usage propre"),
    ACTIVITES_MENAGES_PRODUCTEURS_SERVICES("Activités indifférenciées des ménages producteurs de services pour usage propre"),
    ACTIVITES_ORGANISATIONS_EXTRATERRITORIALES("Activités des organisations extraterritoriales");

    private final String label;

    DomaineActiviteNr(String label) {
        this.label = label;
    }
    public String getLabel() {
        return label;
    }
    

}
