package abdaty_technologie.API_Invest.Entity.Enum;


public enum PaysEmissionRccM {
    AFGHANISTAN("Afghanistan"),
    AFRIQUE_DU_SUD("Afrique du Sud"),
    ALBANIE("Albanie"),
    ALGERIE("Algérie"),
    ALLEMAGNE("Allemagne"),
    ANDORRE("Andorre"),
    ANGOLA("Angola"),
    ANTIGUA_ET_BARBUDA("Antigua-et-Barbuda"),
    ARABIE_SAOUDITE("Arabie saoudite"),
    ARGENTINE("Argentine"),
    ARMENIE("Arménie"),
    AUSTRALIE("Australie"),
    AUTRICHE("Autriche"),
    AZERBAIDJAN("Azerbaïdjan"),
    BAHAMAS("Bahamas"),
    BAHREIN("Bahreïn"),
    BANGLADESH("Bangladesh"),
    BARBADE("Barbade"),
    BELARUS("Bélarus"),
    BELGIQUE("Belgique"),
    BELIZE("Belize"),
    BENIN("Bénin"),
    BHOUTAN("Bhoutan"),
    BOLIVIE("Bolivie"),
    BOSNIE_HERZEGOVINE("Bosnie-Herzégovine"),
    BOTSWANA("Botswana"),
    BRESIL("Brésil"),
    BRUNEI("Brunei"),
    BULGARIE("Bulgarie"),
    BURKINA_FASO("Burkina Faso"),
    BURUNDI("Burundi"),
    CAMBODGE("Cambodge"),
    CAMEROUN("Cameroun"),
    CANADA("Canada"),
    CAP_VERT("Cap-Vert"),
    CHILI("Chili"),
    CHINE("Chine"),
    CHYPRE("Chypre"),
    COLOMBIE("Colombie"),
    COMORES("Comores"),
    CONGO("Congo"),
    CONGO_RDC("Congo (RDC)"),
    COREE_DU_NORD("Corée du Nord"),
    COREE_DU_SUD("Corée du Sud"),
    COSTA_RICA("Costa Rica"),
    COTE_DIVOIRE("Côte d'Ivoire"),
    CROATIE("Croatie"),
    CUBA("Cuba"),
    DANEMARK("Danemark"),
    DJIBOUTI("Djibouti"),
    DOMINIQUE("Dominique"),
    EGYPTE("Égypte"),
    EMIRATS_ARABES_UNIS("Émirats arabes unis"),
    EQUATEUR("Équateur"),
    ERYTHREE("Érythrée"),
    ESPAGNE("Espagne"),
    ESTONIE("Estonie"),
    ESWATINI("Eswatini"),
    ETATS_UNIS("États-Unis"),
    ETHIOPIE("Éthiopie"),
    FIDJI("Fidji"),
    FINLANDE("Finlande"),
    FRANCE("France"),
    GABON("Gabon"),
    GAMBIE("Gambie"),
    GEORGIE("Géorgie"),
    GHANA("Ghana"),
    GRECE("Grèce"),
    GRENADE("Grenade"),
    GUATEMALA("Guatemala"),
    GUINEE("Guinée"),
    GUINEE_BISSAU("Guinée-Bissau"),
    GUINEE_EQUATORIALE("Guinée équatoriale"),
    GUYANA("Guyana"),
    HAITI("Haïti"),
    HONDURAS("Honduras"),
    HONGRIE("Hongrie"),
    INDE("Inde"),
    INDONESIE("Indonésie"),
    IRAN("Iran"),
    IRAK("Irak"),
    IRLANDE("Irlande"),
    ISLANDE("Islande"),
    ISRAEL("Israël"),
    ITALIE("Italie"),
    JAMAIQUE("Jamaïque"),
    JAPON("Japon"),
    JORDANIE("Jordanie"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KIRGHIZISTAN("Kirghizistan"),
    KIRIBATI("Kiribati"),
    KOWEIT("Koweït"),
    LAOS("Laos"),
    LESOTHO("Lesotho"),
    LETTONIE("Lettonie"),
    LIBAN("Liban"),
    LIBERIA("Liberia"),
    LIBYE("Libye"),
    LIECHTENSTEIN("Liechtenstein"),
    LITUANIE("Lituanie"),
    LUXEMBOURG("Luxembourg"),
    MACEDOINE_DU_NORD("Macédoine du Nord"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAISIE("Malaisie"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTE("Malte"),
    MAROC("Maroc"),
    MARSHALL("Îles Marshall"),
    MAURICE("Maurice"),
    MAURITANIE("Mauritanie"),
    MEXIQUE("Mexique"),
    MICRONESIE("Micronésie"),
    MOLDAVIE("Moldavie"),
    MONACO("Monaco"),
    MONGOLIE("Mongolie"),
    MONTENEGRO("Monténégro"),
    MOZAMBIQUE("Mozambique"),
    NAMIBIE("Namibie"),
    NAURU("Nauru"),
    NEPAL("Népal"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORVEGE("Norvège"),
    NOUVELLE_ZELANDE("Nouvelle-Zélande"),
    OMAN("Oman"),
    OUGANDA("Ouganda"),
    OUZBEKISTAN("Ouzbékistan"),
    PAKISTAN("Pakistan"),
    PALAOS("Palaos"),
    PALESTINE("Palestine"),
    PANAMA("Panama"),
    PAPOUASIE_NOUVELLE_GUINEE("Papouasie-Nouvelle-Guinée"),
    PARAGUAY("Paraguay"),
    PAYS_BAS("Pays-Bas"),
    PEROU("Pérou"),
    PHILIPPINES("Philippines"),
    POLOGNE("Pologne"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    REPUBLIQUE_CENTRAFRICAINE("République centrafricaine"),
    REPUBLIQUE_DOMINICAINE("République dominicaine"),
    REPUBLIQUE_TCHEQUE("République tchèque"),
    ROUMANIE("Roumanie"),
    ROYAUME_UNI("Royaume-Uni"),
    RUSSIE("Russie"),
    RWANDA("Rwanda"),
    SAINT_KITTS_ET_NEVIS("Saint-Christophe-et-Niévès"),
    SAINT_MARIN("Saint-Marin"),
    SAINT_VINCENT_ET_LES_GRENADINES("Saint-Vincent-et-les-Grenadines"),
    SAINTE_LUCIE("Sainte-Lucie"),
    SALOMON("Îles Salomon"),
    SALVADOR("Salvador"),
    SAMOA("Samoa"),
    SAO_TOME_ET_PRINCIPE("Sao Tomé-et-Principe"),
    SENEGAL("Sénégal"),
    SERBIE("Serbie"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPOUR("Singapour"),
    SLOVAQUIE("Slovaquie"),
    SLOVENIE("Slovénie"),
    SOMALIE("Somalie"),
    SOUDAN("Soudan"),
    SOUDAN_DU_SUD("Soudan du Sud"),
    SRI_LANKA("Sri Lanka"),
    SUEDE("Suède"),
    SUISSE("Suisse"),
    SURINAME("Suriname"),
    SYRIE("Syrie"),
    TADJIKISTAN("Tadjikistan"),
    TANZANIE("Tanzanie"),
    TCHAD("Tchad"),
    THAILANDE("Thaïlande"),
    TIMOR_ORIENTAL("Timor-Orientale"),
    TOGO("Togo"),
    TONGA("Tonga"),
    TRINITE_ET_TOBAGO("Trinité-et-Tobago"),
    TUNISIE("Tunisie"),
    TURKMENISTAN("Turkménistan"),
    TURQUIE("Turquie"),
    TUVALU("Tuvalu"),
    UKRAINE("Ukraine"),
    URUGUAY("Uruguay"),
    VANUATU("Vanuatu"),
    VATICAN("Vatican"),
    VENEZUELA("Venezuela"),
    VIETNAM("Viêt Nam"),
    YEMEN("Yémen"),
    ZAMBIE("Zambie"),
    ZIMBABWE("Zimbabwe");

      private final String value;

    PaysEmissionRccM(String value) {
        this.value = value;
    }
    public String getValue() {
        return value;
    }
    
}
