version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - investmali-network

  backend:
    image: investmali-backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
    expose:
      - "8080"
    networks:
      - investmali-network

networks:
  investmali-network:
    driver: bridge
